# Site settings
name: Placewise
version: 0.0.1
author: Max Quattromani
email: max@placewise.com
description: ""
baseurl: "/placewise"
url: "http://quattromani.github.io/placewise"
author: "Max Quattromani"
twitter_username: maxquattromani
github_username:  quattromani

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

exclude: ['node_modules', 'scss', 'DAM']

google_analytics: false
google_analytics_id: UA-XXXXXXXX-X
jquery_version: 1.9.0

footer: ""
